# PM~10~ {.tabset}

```{r pm10-options}
knitr::opts_chunk$set(cache = FALSE)

stat_reports<-"./stat-summaries"
```

## Statistical Summary

Note: the stat summary will have one fewer hour for the AQSAS-sourced analysis.

```{r pm10_stats}

pm10_stats<-purrr::map_dfr((data |>
                dplyr::filter(PARAMETER %in% "PM10") |>
                dplyr::distinct(STATION_NAME) |>
                dplyr::arrange(STATION_NAME))$STATION_NAME,

             function(station){

               station<-data |>
                 dplyr::filter(PARAMETER %in% "PM10" &
                                 STATION_NAME %in% station)

               purrr::map_dfr(unique(station$INSTRUMENT),

                 function(instrument){

                   instrument<-station |>
                     dplyr::filter(INSTRUMENT %in% instrument)

                   pm10_stats_fcn(data=instrument,year=params$year)

                 }) #INSTRUMENT LOOP

             }) #STATION LOOP

# add column origin for where calculations originate from
pm10_stats %<>% dplyr::mutate(ORIGIN="AQAS")

```


```{r pm10_stats_aqm}
# get pm10 stations in data
pm10_stns<-data |>
  dplyr::filter(PARAMETER=="PM10") |>
  dplyr::pull(STATION_NAME) |>
  unique(x=_)

if(length(pm10_stns!=0)){

# import _aqm Stats from excel
pm10_stats_aqm <- readxl::read_excel(
  file.path(stat_reports,                                            
            stringr::str_c("PM10_stats_",
                           params$year,
                           ".xlsx",
                           sep=""))
  ) |>

# remove secondary header row
dplyr::slice(-1) |>
  
  # remove quarterly capture (duplicated)
  dplyr::select(-c(`EMS ID`,
                              `NAPS ID`,
                              REGION,
                              OWNER,
                              UNIT)) |>
  # FOR SUMMARY TABLE
  dplyr::mutate(ORIGIN = "AQM") |>
  # FILTER FOR YEAR AND STATIONS
  dplyr::filter(YEAR == params$year &
                  `STATION NAME` %in% stringr::str_replace(pm10_stns, "_", " "))


# MATCH NAMES AND DATA STRUCTURE - ORDER OF DAILY EXCEEDANCES, 98P , 3-YR 98P IS MISMATCHED.

# utils::View(names(pm10_stats_aqm))
# utils::View(names(pm10_stats))
# utils::View(pm10_stats_aqm)
# 
# tibble::tibble(names(pm10_stats_aqm)[c(1:32,34,35,33,37:47,49:52)],
#                names(pm10_stats)) |> utils::View(.)

pm10_stats_aqm %<>%
  dplyr::select(1:32,34,35,33,everything())

names(pm10_stats_aqm) <- names(pm10_stats)

}
 
```


```{r pm10_stats_dt}
if(length(pm10_stns)!=0 ){

  if(exists("pm10_stats_aqm") & nrow(pm10_stats_aqm)!=0){

    # issues with binding, mismatching column formats (character vs integer), not being able to convert from one form to the other. Convert everything to character for data table.

pm10_stats_dt <- bind_rows(
  pm10_stats_aqm |>
    dplyr::mutate_all(as.character) |>
    dplyr::mutate(`STATION NAME` = toupper(`STATION NAME`)),

  pm10_stats |>
    mutate_all(as.character)

) |>
  dplyr::arrange(`STATION NAME`) |>
  dplyr::select(ORIGIN, everything())


   DT::datatable(
    pm10_stats_dt,
    caption = dplyr::if_else(nrow(pm10_stats_aqm)!=0,
                             "AQM and AQAS calculated statistics.There will be one fewer valid hour compared to AQM stats, I'll try to resolve this for next year.",
                             "AQAS calculated statistics. (No summary available from AQM.)"),
    options = list(
      scrollX = TRUE,
      scroller = TRUE,
      scrollY = 300,
      searching = TRUE,
      paging = TRUE,
      pageLength = 25
    )
  )
   
   
  }else{htmltools::tags$p("No Stats summary for this parameter.")}
  }

# case 2: no data for this parameter
if(length(pm10_stns)==0) {
  htmltools::tags$p("There is no data for this parameter.")
}

```

