# Box Plots {.tabset}

```{r box-plot-options}
knitr::opts_chunk$set(cache = FALSE)

station<-data |>
             dplyr::pull(STATION_NAME) |>
             unique(x=_)
```

```{r data-prep}
# add units becuase it is used below and in the plots

# look at all the unique paramters
# data |> dplyr::distinct(PARAMETER)

data %<>%
  dplyr::mutate(UNIT=dplyr::case_when(
    
    PARAMETER %in% c("CO",
                     "NO",
                     "NO2",
                     "NOx",
                     "O3",
                     "SO2",
                     "H2S",
                     "TRS") ~ "ppb",
    
    PARAMETER %in% c("PM10",
                     "PM25") ~ "ug/m3",
    
    PARAMETER == "HUMIDITY" ~ "%",
    
    PARAMETER == "TEMP_MEAN" ~ "deg. C",
    
    PARAMETER == "WDIR_VECT" ~ "deg.",
    
    PARAMETER == "WSPD_SCLR" ~ "m/s"
    
    
    
    
  ))


```


## PM~2.5~

```{r pm25_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("pm25"))

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no PM2.5 data at this station.")}

```


```{r pm25_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    

    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("pm25"))
    
    if(nrow(plot_data)!= nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
       ){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly PM2.5 (",
                              data |>
                                dplyr::filter(PARAMETER %in% toupper("pm25")) |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    } 
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r pm25_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("pm25"))|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly PM2.5 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("pm25")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r pm25_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("pm25"))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly PM2.5 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("pm25")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## PM~10~

```{r pm10_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("pm10"))

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no PM10 data at this station.")}

```

```{r pm10_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data |>
#              dplyr::filter(PARAMETER %in% toupper("pm10")) |>
#              dplyr::pull(STATION_NAME) |>
#              unique)[4])
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("pm10"))
    
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly PM10 (",
                              data |>
                                dplyr::filter(PARAMETER %in% toupper("pm10")) |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r pm10_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("pm10"))|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly pm10 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("pm10")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r pm10_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("pm10"))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly pm10 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("pm10")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```


## O~3~


```{r o3_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("o3"))

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no O3 data at this station.")}

```

```{r o3_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data |>
#              dplyr::filter(PARAMETER %in% toupper("o3")) |>
#              dplyr::pull(STATION_NAME) |>
#              unique)[4])
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("o3"))
    
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly o3 (",
                              data |>
                                dplyr::filter(PARAMETER %in% toupper("o3")) |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r o3_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("o3"))|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly o3 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("o3")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r o3_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("o3"))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly o3 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("o3")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## NO~2~

```{r no2_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("no2"))

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no NO2 data at this station.")}

```

```{r no2_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data |>
#              dplyr::filter(PARAMETER %in% toupper("no2")) |>
#              dplyr::pull(STATION_NAME) |>
#              unique)[4])
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("no2"))
    
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly no2 (",
                              data |>
                                dplyr::filter(PARAMETER %in% toupper("no2")) |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r no2_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("no2"))|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly no2 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("no2")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r no2_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("no2"))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly no2 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("no2")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## NO

```{r no_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("no"))

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no NO data at this station.")}

```

```{r no_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data |>
#              dplyr::filter(PARAMETER %in% toupper("no")) |>
#              dplyr::pull(STATION_NAME) |>
#              unique)[4])
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("no"))
    
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly no (",
                              data |>
                                dplyr::filter(PARAMETER %in% toupper("no")) |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
    plotly::ggplotly(p) 
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r no_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("no"))|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly no (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("no")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r no_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("no"))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly no (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("no")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## NO~x~

```{r nox_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% "NOx")

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no NOx data at this station.")}

```

```{r nox_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data |>
#              dplyr::filter(PARAMETER %in% "NOx") |>
#              dplyr::pull(STATION_NAME) |>
#              unique)[4])
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% "NOx")
    
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly nox (",
                              data |>
                                dplyr::filter(PARAMETER %in% "NOx") |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    } 
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r nox_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% "NOx")|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly nox (",
          data |>
            dplyr::filter(PARAMETER %in% "NOx") |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r nox_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% "NOx")
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly nox (",
          data |>
            dplyr::filter(PARAMETER %in% "NOx") |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## SO~2~

```{r so2_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("so2"))

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no SO2 data at this station.")}

```

```{r so2_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    

    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("so2"))
    
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly so2 (",
                              data |>
                                dplyr::filter(PARAMETER %in% toupper("so2")) |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r so2_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("so2"))|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly so2 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("so2")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r so2_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("so2"))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly so2 (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("so2")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## CO

```{r co_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("co"))

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no CO data at this station.")}

```

```{r co_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    

    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("co"))
    
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly co (",
                              data |>
                                dplyr::filter(PARAMETER %in% toupper("co")) |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r co_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("co"))|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly co (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("co")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r co_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("co"))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly co (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("co")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## TRS

```{r trs_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("trs"))

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no TRS data at this station.")}

```


```{r trs_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    

    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("trs"))
    
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly trs (",
                              data |>
                                dplyr::filter(PARAMETER %in% toupper("trs")) |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r trs_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("trs"))|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly trs (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("trs")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    }
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r trs_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("trs"))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly trs (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("trs")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## H~2~S

```{r h2s_data}

plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("h2s"))

if(nrow(plot_data)== nrow(plot_data |>
                             dplyr::filter(is.na(RAW_VALUE)))
){htmltools::tags$p("There is no H2S data at this station.")}

```

```{r h2s_monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data |>
#              dplyr::filter(PARAMETER %in% toupper("h2s")) |>
#              dplyr::pull(STATION_NAME) |>
#              unique)[4])
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("h2s"))
    
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p<-ggplot2::ggplot(data = plot_data,
           ggplot2::aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = RAW_VALUE,
               fill=STATION_NAME)
           ) +
      ggplot2::geom_boxplot() +
      ggplot2::labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly h2s (",
                              data |>
                                dplyr::filter(PARAMETER %in% toupper("h2s")) |>
                                dplyr::pull(UNIT) |> unique(x=_), ")",
                              sep = ""
             )
           ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        ggplot2::scale_fill_brewer(palette = "Set1")+
      ggplot2::facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r h2s_hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("h2s"))|>
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data ,
      ggplot2::aes(
        x = weekday,
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly h2s (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("h2s")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r h2s_diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(station,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plot_data<-data |> 
             dplyr::filter(STATION_NAME %in% station &
                             PARAMETER %in% toupper("h2s"))
    if(nrow(plot_data)!=plot_data |> 
      dplyr::summarise(nas=sum(is.na(RAW_VALUE))) |>
      dplyr::pull(nas)){
    
    p <- ggplot2::ggplot(
      data = plot_data,
      ggplot2::aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = RAW_VALUE,
        fill = STATION_NAME
      )
    ) +
      ggplot2::geom_boxplot() +
      ggplot2::scale_x_discrete()+
      ggplot2::labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly h2s (",
          data |>
            dplyr::filter(PARAMETER %in% toupper("h2s")) |>
            dplyr::pull(UNIT) |> unique(x=_),
          ")",
          sep = ""
        )
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      ggplot2::scale_fill_brewer(palette = "Set1") +
      ggplot2::facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } 
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```
