# Histograms {.tabset}


```{r boxPlotOptions}
knitr::opts_chunk$set(cache = TRUE)
```

```{r testing}
station <- data %>%
  dplyr::filter(PARAMETER %in% toupper("PM25")) %>%
  dplyr::pull(STATION_NAME_FULL) %>%
  unique

plotData <- data %>%
  dplyr::filter(STATION_NAME_FULL %in% station &
                  PARAMETER %in% toupper("pm25"))




```


## PM~2.5~

```{r pm25monthly}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("PM25")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("PM25")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("pm25"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly PM2.5 (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("pm25")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no PM2.5 data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r pm25hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("PM25")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("pm25"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly PM2.5 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("pm25")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no PM2.5 data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r pm25diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("PM25")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("pm25"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly PM2.5 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("pm25")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no PM2.5 data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## PM~10~

```{r pm10monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("pm10")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("pm10")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("pm10"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly PM10 (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("pm10")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no PM10 data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r pm10hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("pm10")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("pm10"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly pm10 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("pm10")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no pm10 data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r pm10diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("pm10")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("pm10"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly pm10 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("pm10")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no pm10 data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```


## O~3~

```{r o3monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("o3")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("o3")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("o3"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly o3 (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("o3")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no o3 data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r o3hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("o3")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("o3"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly o3 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("o3")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no o3 data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r o3diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("o3")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("o3"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly o3 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("o3")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no o3 data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## NO~2~

```{r no2monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("no2")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("no2")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("no2"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly no2 (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("no2")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no no2 data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r no2hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("no2")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("no2"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly no2 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("no2")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no no2 data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r no2diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("no2")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("no2"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly no2 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("no2")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no no2 data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## NO

```{r nomonthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("no")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("no")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("no"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly no (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("no")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no no data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r nohebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("no")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("no"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly no (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("no")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no no data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r nodiurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("no")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("no"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly no (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("no")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no no data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## NO~x~


```{r noxmonthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("nox")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("nox")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("nox"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly nox (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("nox")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no nox data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r noxhebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("nox")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("nox"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly nox (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("nox")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no nox data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r noxdiurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("nox")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("nox"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly nox (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("nox")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no nox data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## SO~2~

```{r so2monthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("so2")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("so2")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("so2"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly so2 (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("so2")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no so2 data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r so2hebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("so2")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("so2"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly so2 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("so2")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no so2 data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r so2diurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("so2")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("so2"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly so2 (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("so2")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no so2 data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## CO

```{r comonthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("co")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("co")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("co"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly co (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("co")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no co data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r cohebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("co")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("co"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly co (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("co")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no co data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r codiurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("co")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("co"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly co (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("co")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no co data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## TRS


```{r trsmonthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("trs")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("trs")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("trs"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly trs (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("trs")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no trs data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r trshebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("trs")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("trs"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly trs (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("trs")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no trs data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r trsdiurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("trs")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("trs"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly trs (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("trs")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no trs data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

## H~2~S

```{r h2smonthly}

suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("h2s")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
    
  
    {
    
    #FOR TESTING - 9 total
# (station<-(data %>%
#              dplyr::filter(PARAMETER %in% toupper("h2s")) %>%
#              dplyr::pull(STATION_NAME_FULL) %>%
#              unique)[4])
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("h2s"))
    
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p<-ggplot(data = plotData,
           aes(x = reorder(format(DATE_PST, "%b"), DATE_PST), #alter this for different boxplots
               y = ROUNDED_VALUE,
               fill=STATION_NAME_FULL)
           ) +
      geom_boxplot() +
      labs(title = paste("Monthly Boxplot:",
                         station),
           x = "",
           y = stringr::str_c("Hourly h2s (",
                              data %>%
                                dplyr::filter(PARAMETER %in% toupper("h2s")) %>%
                                dplyr::pull(UNIT) %>% unique, ")",
                              sep = ""
             )
           ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      )+ 
        scale_fill_brewer(palette = "Set1")+
      facet_wrap( ~ INSTRUMENT, scales = "free") 
    
  # Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    plotly::ggplotly(p) 
    
    }  else{paste("There is no h2s data for",station)}#end if and else
      
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```

```{r h2shebdomadal}
suppressWarnings(
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("h2s")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("h2s"))%>%
        dplyr::mutate(weekday=factor(format(DATE_PST,"%a"),
                                     c("Sun",
                                        "Mon",
                                        "Tue",
                                        "Wed",
                                        "Thu",
                                        "Fri",
                                        "Sat")))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData ,
      aes(
        x = weekday,
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Hebdomadal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly h2s (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("h2s")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no h2s data for",station)}#end if and else
    
      
    } #end plot function
  
  )# end map
  
) #end tagList

) # end suppressWarnings

```

```{r h2sdiurnal}
suppressWarnings(
  
  htmltools::tagList(
  
  purrr::map(data %>%
             dplyr::filter(PARAMETER %in% toupper("h2s")) %>%
             dplyr::pull(STATION_NAME_FULL) %>%
             unique,
  
  function(station)
  # station<-"Abbotsford A Columbia Street"
    {
    plotData<-data %>% 
             dplyr::filter(STATION_NAME_FULL %in% station &
                             PARAMETER %in% toupper("h2s"))
    if(nrow(plotData)!=plotData %>% 
      dplyr::summarise(nas=sum(is.na(ROUNDED_VALUE))) %>%
      dplyr::pull(nas)){
    
    p <- ggplot(
      data = plotData,
      aes(
        x = format(DATE_PST,"%H"),
        #alter this for different boxplots
        y = ROUNDED_VALUE,
        fill = STATION_NAME_FULL
      )
    ) +
      geom_boxplot() +
      scale_x_discrete()+
      labs(
        title = paste("Diurnal Boxplot:",station),
        x = "",
        y = stringr::str_c(
          "Hourly h2s (",
          data %>%
            dplyr::filter(PARAMETER %in% toupper("h2s")) %>%
            dplyr::pull(UNIT) %>% unique,
          ")",
          sep = ""
        )
      ) +
      theme_bw() +
      theme(
        # axis.text.x = element_text(
        #   # angle = 60,
        #   vjust = 1,
        #   hjust = 1
        # ),
        legend.position = "none",
        legend.title = element_blank()
      ) +
      scale_fill_brewer(palette = "Set1") +
      facet_wrap(~ INSTRUMENT, scales = "free")
    
    plotly::ggplotly(p)
    
    } else{paste("There is no h2s data for",station)}#end if and else
    
    } #end plot function
  
  )# end map
  
) #end tagList

) #end suppressWarnings

```
