# Wind Roses

```{r windCache}
knitr::opts_chunk$set(cache = FALSE)
```


```{r windDataPrep}
# select wind data, get it in openair format

windData <- data %>%
  
  dplyr::filter(PARAMETER %in% c("WSPD_SCLR", "WDIR_VECT")) %>%
  dplyr::bind_rows(.,
                   prevYrWind)

#find duplicates
windData %>% 
  dplyr::group_by(STATION_NAME,PARAMETER,INSTRUMENT,DATE_PST) %>%
  dplyr::filter(n()>1)


if( all(nrow(windData)!=0, # at least one row of data
        any(unique(windData$PARAMETER) %in% "WSPD_SCLR"),
        any(unique(windData$PARAMETER) %in% "WDIR_VECT")
    )
  ){
  
  windData %<>%
    
    dplyr::select(date = DATE_PST,
                  STATION_NAME,
                  PARAMETER,
                  RAW_VALUE) %>%
    
    tidyr::pivot_wider(.,
                       names_from = PARAMETER,
                       values_from = RAW_VALUE) %>%
    
    dplyr::rename(ws = WSPD_SCLR,
                  wd = WDIR_VECT) %>%
    
    dplyr::mutate(ws = ifelse(is.na(wd), NA, ws),
                  wd = ifelse(is.na(ws), NA, wd))
}

  

```

```{r windRose}
if(all(nrow(windData)!=0, # at least one row of data
        any(names(windData) %in% "ws"),
        any(names(windData) %in% "wd")

    )
) {
  

purrr::walk(unique(lubridate::year(windData$date)) %>% sort,
    
    function(year){
      
      # TESTING
      
      # year<-yearToValidate
      
      # END TESTING
      
      station<-unique(windData$STATION_NAME)
      
      windData %<>%
        dplyr::filter(lubridate::year(date) %in% year)
      
      if(nrow(windData)==sum(is.na(windData$ws))){
        
        paste("There is no paired wind data at",station)
        
      } else {
      
      #number of calm hours
      ncalm <- windData %>%
        dplyr::filter(ws < 0.5) %>%
        dplyr::summarise(calms = n())
      
      #total number of valid ws hours
      ntotal <- windData %>%
        dplyr::filter(!is.na(ws)) %>%
        dplyr::summarise(total = n())
      
      #percentage calm (ws<0.5 m/s)
      pcalm <- round(100 * ncalm / ntotal,
                     digits = 2)
      
      #filter out calm windData
      roseData <- windData %>%
        dplyr::filter(ws >= 0.5)
      
      #windRose
      windRose(
        roseData,
        annotate = FALSE,
        breaks = c(0.5, 1.5, 3.3, 5.5, 7.9, 10.7, 13.8, 17.1),
        #Beaufort scale with 0.5 as lowest cut point.
        sub = paste("Calms (=<0.5m/s)=", pcalm, "%"),
        key.position = "right",
        main = stringr::str_c(year," Wind Rose at ",station),
        angle = 360 / 16,
        #16 spokes
        cols = "jet",
        paddle = FALSE
      ) 
      
      } # end else
      
    } #end function(station)
    
    ) # map
  
} else{
  
  htmltools::tags$p("This station either doesn't measure wind, or it is missing one of WSPD_SCLR or WDIR_VECT")
  
}


```
