---
title: "Import and Prep Data"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(magrittr)
library(envair)
```

```{r importPrevYrWind}

# import previous x years wind data for comparison
prevYrWind <- envair::importBC_data(
  parameter_or_station = c("wdir_vect",
                           "wspd_sclr"),
  years = (yearToValidate - 6):(yearToValidate - 1),
  use_openairformat = FALSE
) %>%
  dplyr::filter(lubridate::year(DATE_PST)!=yearToValidate)

#save prevYrWind
readr::write_rds(prevYrWind,
                 "prevYrWind_raw.rds")
```

```{r strip_60}
prevYrWind<-readr::read_rds("prevYrWind.rds")
# issue: when datalogger is switched to campbell ""_60|_MET_60| MET_60" is appended to STATION_NAME_FULL. we want same id's for same station
#fix: strip "_60|_MET_60| MET_60" from station names

# testing to confirm regex and stringr package work as intended
prevYrWind %>%
  dplyr::distinct(STATION_NAME,
                  STATION_NAME_FULL) %>%
  dplyr::filter(stringr::str_detect(STATION_NAME_FULL,
                                    "_60|_MET_60| MET_60")) %>%
  dplyr::mutate(STATION_NAME_FULL=stringr::str_remove(STATION_NAME_FULL,
                                                       "_60|_MET_60| MET_60")
                
                ) %>%
  dplyr::distinct(STATION_NAME,
                  STATION_NAME_FULL)


# change the data in prevYrWind
prevYrWind %<>%
  dplyr::mutate(STATION_NAME_FULL=stringr::str_remove(STATION_NAME_FULL,
                                                       "_60|_MET_60| MET_60")
                )

# have a look
prevYrWind %>% 
  dplyr::distinct(STATION_NAME,
                  STATION_NAME_FULL)

#save prevYrWind
readr::write_rds(prevYrWind,
                 "prevYrWind.rds")
```


```{r prevYrWindYears}
prevYrWind<-readr::read_rds("prevYrWind.rds")

# check what years were imported
prevYrWind %>%
  dplyr::distinct(year=lubridate::year(DATE_PST)) %>%
  dplyr::arrange(year)# imports data in years that were not requested
  
prevYrWind %<>%  # filter for last X years of data (double check):
  dplyr::filter(lubridate::year(DATE_PST) %in% (yearToValidate - 6):(yearToValidate - 1)) %>%
  dplyr::distinct(.)

#save prevYrWind
readr::write_rds(prevYrWind,
                 "prevYrWind.rds")
```

```{r prevYrWindNAs}
prevYrWind<-readr::read_rds("prevYrWind.rds")

# check if there are NA's for STATION_NAME_FULL and for VALIDATION_STATUS
prevYrWind %>%
  dplyr::filter(is.na(STATION_NAME_FULL) & is.na(VALIDATION_STATUS)) #5,468,551 rows

# if it's the same number as is.na(STATION_NAME_FULL) | is.na(VALIDATION_STATUS),
# then it's always both of them that are NA
prevYrWind %>%
  dplyr::filter(is.na(STATION_NAME_FULL) | is.na(VALIDATION_STATUS)) #5,468,551 rows
# the above shows that STATION_NAME_FULL is always NA when VALIDATION_STATUS is NA

# summary of when these NA's occur:
prevYrWind %>%
  dplyr::filter(is.na(STATION_NAME_FULL) & is.na(VALIDATION_STATUS)) %>%
  dplyr::group_by(year=lubridate::year(DATE_PST),
                  STATION_NAME_FULL,
                  STATION_NAME,
                  PARAMETER) %>%
  dplyr::summarise(`# NA's`=n()) # there are lots of them at different stations, 
# in different years and for both WDIR_VECT and WSPD_SCLR

# filter out these NA's
prevYrWind %<>%
  dplyr::filter(!(is.na(STATION_NAME_FULL) & is.na(VALIDATION_STATUS))) #reduces 
# data set by ~5 million obs!

#save prevYrWind
readr::write_rds(prevYrWind,
                 "prevYrWind.rds")
```

```{r prevYrWindValidationStatus}
prevYrWind<-readr::read_rds("prevYrWind.rds")

# years 2016-2022 should only have 
# validation status =  Level 2. check this

#this summarises data that has more than one validation status in a single year
prevYrWind %>%
  dplyr::group_by(YEAR=lubridate::year(DATE_PST),
                  STATION_NAME_FULL,
                  STATION_NAME,
                  PARAMETER,
                  VALIDATION_STATUS,
                  INSTRUMENT) %>%
  dplyr::summarise(n=n()) %>% 
  dplyr::ungroup() %>%
  dplyr::group_by(YEAR,
                  STATION_NAME_FULL,
                  STATION_NAME,
                  PARAMETER,
                  INSTRUMENT) %>%
  dplyr::filter(n()>1) %>% utils::View(.) # shows that many stations have 1 hour of level 2 validation status and the rest are level 0.also that this only happens in 2021

#save prevYrWind
readr::write_rds(prevYrWind,
                 "prevYrWind.rds")

#easier to do this graphically:

STATION_NAME_FULL<-prevYrWind %>% dplyr::distinct(STATION_NAME_FULL) %>% dplyr::pull(STATION_NAME_FULL)

plotList<-purrr::map(STATION_NAME_FULL, 
                     function(x) {
  
  ggplot2::ggplot(
    prevYrWind %>%
      # dplyr::mutate(year=lubridate::year(DATE_PST)) %>%
      dplyr::filter(STATION_NAME_FULL == x),
    aes(
      x = DATE_PST,
      y = VALIDATION_STATUS,
      color = VALIDATION_STATUS,
      shape = INSTRUMENT
    )
  ) +
    ggplot2::geom_point(alpha = 0.6) +
    ggplot2::facet_grid(rows=vars(PARAMETER)) +
    ggplot2::theme_bw() +
    ggplot2::labs(title = x) +
    ggplot2::scale_color_viridis_d()
  
})

pdf(file="prevYrWind_ValidationStatus.pdf")

purrr::walk(plotList,print)

dev.off()

# 2023 I am goign to leave this for this year and make everything one validation status to avoid errors/crashes. 
```

```{r prevYrWindValStatus}

# look for duplicates within each validation status in the hourly data:
duplicates <- prevYrWind %>%
  dplyr::group_by(DATE_PST,
                  STATION_NAME_FULL,
                  STATION_NAME,
                  PARAMETER,
                  VALIDATION_STATUS,
                  INSTRUMENT) %>% 
  dplyr::summarise(n = dplyr::n(),
                   .groups = "drop") %>%
  dplyr::filter(n > 1L) %>%
  dplyr::left_join(
    .,
    prevYrWind,
    by = c(
      "DATE_PST",
      "STATION_NAME_FULL",
      "STATION_NAME",
      "PARAMETER",
      "VALIDATION_STATUS",
      "INSTRUMENT"
    )
  ) %>%
  
  dplyr::arrange(DATE_PST,
                 STATION_NAME,
                 STATION_NAME_FULL,
                 PARAMETER) %>%
  dplyr::select(
    DATE_PST,
    STATION_NAME,
    STATION_NAME_FULL,
    PARAMETER,
    INSTRUMENT,
    RAW_VALUE,
    everything()
  )
# no duplicates!

# all of the level 0 validation status in 2021 occurs jan 1 00:00, but not at all stations
prevYrWind %>%
  dplyr::filter(lubridate::year(DATE_PST)==2021) %>%
  dplyr::group_by(STATION_NAME_FULL,
                  STATION_NAME,
                  PARAMETER,
                  VALIDATION_STATUS) %>%
  dplyr::summarise(start=min(DATE_PST),
                   end=max(DATE_PST),
                   .groups = "drop") %>%
  dplyr::arrange(STATION_NAME,
                 STATION_NAME_FULL,
                 PARAMETER,
                VALIDATION_STATUS) %>% #utils::View(.)
  dplyr::ungroup() %>%
  dplyr::filter(VALIDATION_STATUS=="Level 2") %>%
  dplyr::distinct(STATION_NAME_FULL,start,end)

# fix - make all data prevYrWind have "Level 2" VALIDATION_STATUS
prevYrWind %<>%
  dplyr::mutate(VALIDATION_STATUS="Level 2")

#save prevYrWind
readr::write_rds(prevYrWind,
                 "prevYrWind.rds")
```

```{r windDuplicates}
prevYrWind<-readr::read_rds("prevYrWind.rds")

# DESCRIPTION OF THE ISSUE: there should be a single data set of wind speed and direction for each unique station name, but sometimes wind speed data get split between, for example STATION_NAME AND STATION_NAME_60, or between two different but arbitrary INSTRUMENT fields. CAUSES ISSUES WHEN GENERATING WIND ROSES.

# have a closer look at station_name_full
summary_stnNameFull<-prevYrWind %>%
  dplyr::group_by(STATION_NAME,
                  STATION_NAME_FULL,
                  PARAMETER,INSTRUMENT) %>%
  dplyr::summarise(start=min(DATE_PST),
                   end=max(DATE_PST),
                   n=n(),
                   `values`=sum(!is.na(RAW_VALUE)),
                   `NAs`=sum(is.na(RAW_VALUE)),
                   `allNAs`=n()==sum(is.na(RAW_VALUE)))

utils::View(summary_stnNameFull)

# find combo's that are all NA's and remove them from prevYrWind:
prevYrWind<-summary_stnNameFull %>%
  dplyr::filter(allNAs==TRUE) %>% #utils::View(.)
  dplyr::select(STATION_NAME,
                STATION_NAME_FULL,
                PARAMETER,
                INSTRUMENT) %>%
  dplyr::anti_join(
    prevYrWind,
    .,
    by=c("STATION_NAME",
         "STATION_NAME_FULL",
         "PARAMETER",
         "INSTRUMENT")
  )

#save prevYrWind
readr::write_rds(prevYrWind,
                 "prevYrWind.rds")

#read windDuplicates
windDuplicates<-readr::read_rds("windDuplicates.rds")

# # # # # FIND DUPLICATES
 windDuplicates<-prevYrWind %>%
   
   dplyr::select(DATE_PST,
                 STATION_NAME,
                 PARAMETER,
                 INSTRUMENT,
                 RAW_VALUE) %>%
   
    dplyr::group_by(DATE_PST, 
                    STATION_NAME, 
                    PARAMETER,
                    INSTRUMENT) %>%
   
    dplyr::summarise(n = dplyr::n(), 
                     .groups = "drop") %>%
   
    dplyr::filter(n > 1L) %>%
   
    dplyr::left_join(.,
                    prevYrWind,
                    by=c("DATE_PST",
                         "STATION_NAME", 
                         "PARAMETER",
                         "INSTRUMENT")) %>%
   
   dplyr::select(DATE_PST,
                 STATION_NAME,
                 STATION_NAME_FULL,
                 PARAMETER,
                 INSTRUMENT,
                 RAW_VALUE) %>%
   
    dplyr::arrange(DATE_PST,
                  STATION_NAME,
                  PARAMETER,
                  INSTRUMENT,
                  STATION_NAME_FULL) %>%
   
   dplyr::group_by(DATE_PST,
                   STATION_NAME,
                   PARAMETER,
                   INSTRUMENT) %>%
   
   dplyr::mutate(result=dplyr::case_when(
     
     sum(is.na(RAW_VALUE))==0 ~ "2 values",
     
     sum(is.na(RAW_VALUE))==1 ~ "1 value, 1 NA",
     
     sum(is.na(RAW_VALUE))==2 ~ "2 NAs"
     
   )) %>%
   
   dplyr::ungroup(.)
 
 #save windDuplicates
readr::write_rds(windDuplicates,
                 "windDuplicates.rds")
```

```{r windDuplicatesExploration}
#read windDuplicates
windDuplicates<-readr::read_rds("windDuplicates.rds")


 #preview each case
 utils::View(windDuplicates %>%
               dplyr::group_by(STATION_NAME,
                               result)%>%
               dplyr::slice(1:2))
 
 
 #summarise distinct combinations
 windDuplicates %>%
   dplyr::distinct(STATION_NAME,
                   STATION_NAME_FULL,
                   PARAMETER,
                   INSTRUMENT,
                   result) %>% utils::View(.)
```


```{r windDuplicatesDuncanFix}
# issue: Duncan Cairnsmore and Duncan College Street both have STATION_NAME = Duncan
# fix: change STATION name to unique identifier (i.e. Duncan College Street and Duncan Cairnsmore)

prevYrWind<-readr::read_rds("prevYrWind.rds")

prevYrWind %<>%
  dplyr::mutate(STATION_NAME=dplyr::case_when(
    stringr::str_detect(STATION_NAME_FULL,
                        "DUNCAN CAIRNSMORE") ~ "Duncan Cairnsmore",
    
    stringr::str_detect(STATION_NAME_FULL,
                        "DUNCAN COLLEGE STREET") ~ "Duncan College Street",
    .default=STATION_NAME
    
  )) 

#save prevYrWind
readr::write_rds(prevYrWind,
                 "prevYrWind.rds")
```

```{r windDuplicatesFixes}


# fix duplicates
#1. fix duplicates
#2. replace data in prevYrWind with fixed data
# Note: whatever is done for Duncan (Cairnsmore and College Street) will have to be repeated in data
 
 windDuplicates %>%
   dplyr::group_by(DATE_PST,
                   STATION_NAME,
                   PAREMETER,
                   INSTRUMENT) %>%
   dplyr::summarise(.)
   
   
   dplyr::filter(stringr::str_detect(STATION_NAME,"Duncan")) %>% utils::View(.)

```

```{r data}
# bind the two data sets together, call it data
data<-dplyr::bind_rows(readr::read_rds("unverified_data.rds"),
                       readr::read_rds("prevYrWind.rds")
) %>% 
  dplyr::distinct(.)
```

```{r saveExternally}
# save list of stations in yearToValidate with data:
allStations<-data %>%
  dplyr::filter(lubridate::year(DATE_PST) == yearToValidate) %>%
  dplyr::group_by(STATION_NAME) %>%
  dplyr::filter(!is.na(RAW_VALUE)) %>%
  dplyr::distinct(STATION_NAME) %>%
  dplyr::arrange(STATION_NAME)

# save allStations as rds
readr::write_rds(allStations,
        "allStations.rds")

# read in allStations
# allStations<-readr::read_rds(file="allStations.rds")

# save allStations as csv
readr::write_csv(allStations,
                 "allStations.csv")

# create preppedData folder if it doesn't already exist
ifelse(dir.exists(file.path("./preppedData")),
       "preppedData folder already exists",
       dir.create(file.path("./preppedData"
       )))

# Save each station to preppedData folder 
purrr::walk(readr::read_rds("allStations.rds")$STATION_NAME,
            
            function(x) {
                # test
                # x<-"Abbotsford A Columbia Street"
                # end test
              
                stnData <- data %>%
                dplyr::filter(STATION_NAME == x)
             
                 readr::write_rds(stnData,
                      file.path("./preppedData",
                                stringr::str_c(x, ".rds", collapse = "")))
              
            })
```

