---
title: "Annual Data Validation"
author: "Air Quality Section | Environmental Monitoring and Analysis Branch"
date: "`r format(Sys.time(), '%B %d, %Y')`"
params:
prepped_data: !r stringr::str_c("./prepped-data/",dir('./prepped-data')[3],collapse="")
year: 2024
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config:
      toc:
        collapse: section
---

```{r setup,echo=FALSE,warning=FALSE,message=FALSE}
# To do's for next year:
# - add range slider to plotly so it's easy to pan along axes:
 #(https://plotly.com/r/range-slider/)
# - round aqs stats to match ecms
# - add difference row to sas summary

knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      echo = FALSE)

library(tidyverse)
library(openair)
library(Hmisc)
library(xts)
library(plotly)
library(RCurl)
library(DT)
library(feather)
library(magrittr)
library(readxl)
library(gdata)

# functions to calculate SAS stats from hourly data
source("./stat-summary-fcns/pm25-stats-fcn.R")
source("./stat-summary-fcns/pm10-stats-fcn.R")
source("./stat-summary-fcns/no2-stats-fcn.R")
source("./stat-summary-fcns/no-stats-fcn.R")
source("./stat-summary-fcns/so2-stats-fcn.R")
source("./stat-summary-fcns/o3-stats-fcn.R")
source("./stat-summary-fcns/h2s-stats-fcn.R")
source("./stat-summary-fcns/trs-stats-fcn.R")
source("./stat-summary-fcns/co-stats-fcn.R")

source("plotly-fcn.R")
source("empty-plot.R")
```

```{r import-data}
#use the line below for automated report generation
data<-readr::read_rds(params$prepped_data)

#LOOK FOR DUPLICATES
# duplicates<-data %>%
#     dplyr::group_by(DATE_PST, STATION_NAME, PARAMETER) %>%
#     dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
#     dplyr::filter(n > 1L) %>%
#    dplyr::left_join(.,
#                     data,
#                     by=c("DATE_PST","STATION_NAME","PARAMETER"))
# 
# utils::View(duplicates)

#LOOK FOR DUPLICATES
# duplicates<-data %>%
#     dplyr::group_by(DATE_PST, STATION_NAME, PARAMETER) %>%
#     dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
#     dplyr::filter(n > 1L) %>%
#    dplyr::left_join(.,
#                     data,
#                     by=c("DATE_PST","STATION_NAME","PARAMETER"))
# 
# utils::View(duplicates)

#use the line below for testing - comment it out and pick a station with the parameter(s) of interest
# data<-readRDS("./preppedData/Kelowna.rds")

prev_yrs_wind<-data |> 
  dplyr::filter(lubridate::year(DATE_PST)!=params$year &
                  PARAMETER %in% c("WSPD_SCLR","WDIR_VECT"))

data %<>%
<<<<<<< HEAD
  dplyr::filter(lubridate::year(DATE_PST)==params$year) |>
  dplyr::group_by(PARAMETER,INSTRUMENT) |>
  dplyr::filter(!all(is.na(RAW_VALUE))) |> 
  dplyr::ungroup(x=_)
=======
  dplyr::filter(lubridate::year(DATE_PST)==params$year) %>%
  dplyr::group_by(PARAMETER,INSTRUMENT) %>%
  dplyr::filter(!all(is.na(RAW_VALUE))) %>% 
  dplyr::ungroup(.)
>>>>>>> 49183c6c57e520f93bec0620956181b1901e467b
```


```{r daily-data}
day<-data |>
    # rename to date for openair
    dplyr::rename(date=DATE_PST) %>%
    dplyr::group_by(STATION_NAME,PARAMETER,INSTRUMENT) %>%
    dplyr::group_modify(~ openair::timeAverage(.x,
                                               pollutant="RAW_VALUE",
                                               avg.time = "day",
                                               data.thresh = 75)
    ) %>%
    ungroup %>%
    dplyr::rename(DATE_PST=date)

`24hr`<-data %>%
    # rename to date for openair
    dplyr::rename(date=DATE_PST) %>%
    dplyr::group_by(STATION_NAME,PARAMETER,INSTRUMENT) %>%
    dplyr::group_modify(~ openair::rollingMean(.x,
                                               pollutant="RAW_VALUE",
                                               width = 24,
                                               align = "right",
                                               data.thresh = 75,
                                               new.name = "RAW_VALUE")
    ) %>%
    ungroup %>%
    dplyr::rename(DATE_PST=date)

```


```{r hourly-and-daily}

# combine hourly and day data sets in one tidy tibble
all_data<-data %>%
  dplyr::select(names(day)) %>%
  dplyr::mutate(TIME_AVG = "Hourly") %>%
  dplyr::bind_rows(.,
                   day %>%
                     dplyr::mutate(TIME_AVG = "Daily")) %>%
  dplyr::bind_rows(.,
                   `24hr` %>%
                     dplyr::mutate(TIME_AVG = "24-HR Running Ave"))
```


# Preamble {-}

**This report is for `r data %>% dplyr::pull(STATION_NAME) %>% unique %>% sort`**.